### PR TITLE
Add support for the 5000 series

### PR DESCRIPTION
**Pull request by Lorac**
Fixes no official issue.

Add the variant 5204, the one that I can test right now.

### CODE REVIEW

**Comment by Lorac** [comment]
Hello @hsmistry,

I'm trying to find the frequencies for these fields in the documentation (pdf)
```
        self.info.siggen_frequency = 1000000
        self.info.siggen_min = 0
        self.info.siggen_max = 4000000
```

Are they the same as the ps5000a variant?

**Comment by hsmistry** [comment]
Hi @Lorac,  

self.info.siggen_min = 0
self.info.siggen_max = 4000000

is correct as this is minimum and maximum peak-to-peak voltage

The max value for self.info.siggen_frequency is 20000000 as per the ps5000Api.h file

Hope this helps.

**Comment by Lorac** [comment]
@hsmistry Thanks, I submitted the changes you asked for.

**Comment by hsmistry** [comment]
Thanks @Lorac, is there another commit that will be pushed up?

**Comment by Lorac** [comment]
@hsmistry No new commit, just updated the current one.

**Comment by Lorac** [comment]
It looks like ps5000base.py needs some of modification to make it work, and it brings incompatibility with other pico in the 5000 series.

ps5000 `GetTimebase` takes a `c_uint16` for segment, but the 5000a take a `c_uint32`. Same thing for `GetValues`.

**Comment by Lorac** [comment]
There is a different interface for triggers on the 5204, I added it to the ps5000.py and moved the other one to ps5000a.py.

**Comment by Lorac** [comment]
It has a different set_channel interface too, I added the implementation inside ps5000.py.

**Comment by Lorac** [comment]
I made a mistake when I created this pull request. I created it from my `master`... I created another branche based off my current master so that I can continue to merge.

I'll close this one and create another pull request from the other branch and will reference this pull request.

**Pull request closed without merging**
